### ISSUE TITLE
scroll-up-bar.min.js on a CDN?

### ISSUE THREAD

**Issue by tiagogon** [eduardomb/scroll-up-bar#19]
is scroll-up-bar.min.js available or is going to be available on a CDN like https://cdnjs.com ? it would be cool ;) 

thanks for the great work here! ;)

**Comment by rstacruz** [comment]
sure.

https://cdn.rawgit.com/eduardomb/scroll-up-bar/0.3.0/dist/scroll-up-bar.min.js

**Comment by tiagogon** [comment]
lovely!
