### ISSUE TITLE
Would you add a License?

### ISSUE THREAD

**Issue by jonlay** [eduardomb/scroll-up-bar#23]
Hey @eduardomb! Thanks for a great little plugin.

Do you have plans to add a [license](https://help.github.com/articles/open-source-licensing/) to the repo? Right now, it's not actually legally permissible to use it on any projects :wink:

**Comment by eduardomb** [comment]
Thanks for remembering! I've just added it on https://github.com/eduardomb/scroll-up-bar/commit/5b5d3da9814b42cec7efc640480e9ac5315cbc31:  https://github.com/eduardomb/scroll-up-bar/blob/master/LICENSE.md.

**Comment by jonlay** [comment]
Thanks a lot! :+1:
